import { z } from "zod";
import { readFile } from "fs/promises";
import { resolve } from "path";

// ── Config file schema ──────────────────────────────────────────────────────

export const AgentConfigSchema = z.object({
  /** Base URL of the MCP Central server (e.g. https://mcp.example.com) */
  serverUrl: z.string().url("serverUrl must be a valid URL"),
  /** Display name of this agent — must match the name used when creating the agent */
  agentName: z.string().min(1, "agentName is required"),
  /** Agent API key starting with 'agent_' (generated by MCP Central) */
  apiKey: z
    .string()
    .min(10, "apiKey is too short")
    .refine((k) => k.startsWith("agent_"), {
      message: "apiKey must start with 'agent_'",
    }),
});

export type AgentConfig = z.infer<typeof AgentConfigSchema>;

// ── Config loader ──────────────────────────────────────────────────────────

/**
 * Loads and validates the agent configuration from a JSON file.
 * Defaults to `mcp-agent.json` in the current working directory.
 */
export async function loadConfig(filePath?: string): Promise<AgentConfig> {
  const configPath = resolve(filePath ?? "mcp-agent.json");
  let raw: string;
  try {
    raw = await readFile(configPath, "utf-8");
  } catch {
    throw new Error(
      `Config file not found: ${configPath}\n` +
        `Run 'mcp-central-agent init' to create one.`,
    );
  }

  let json: unknown;
  try {
    json = JSON.parse(raw);
  } catch (err) {
    throw new Error(`Invalid JSON in ${configPath}: ${String(err)}`);
  }

  const result = AgentConfigSchema.safeParse(json);
  if (!result.success) {
    const issues = result.error.issues
      .map((i) => `  • ${i.path.join(".")}: ${i.message}`)
      .join("\n");
    throw new Error(`Invalid config in ${configPath}:\n${issues}`);
  }
  return result.data;
}
